### ISSUE TITLE
Fedora - `sh: file: command not found`

### ISSUE THREAD

**Issue by schloerke** [r-hub/rhub-server#26] opened 2019-03-07 15:09 UTC
* Live example: 
  * https://builder.r-hub.io/status/reactlog_1.0.0.tar.gz-2a15acc55edd41e6bef5025f112f0470#L1152
* Build ID: 
  * reactlog_1.0.0.tar.gz-2a15acc55edd41e6bef5025f112f0470
* Platform: 
  * Fedora Linux, R-devel, clang, gfortran

**Comment by gaborcsardi** [comment] 2019-03-08 09:22
Duplicate of this: https://github.com/r-hub/rhub/issues/216

**Closed by gaborcsardi** 2019-03-08 09:22 UTC
